export enum MessageTypes {
    NEW_GAME = 'NEW_GAME',
    START_REQUEST = 'START_REQUEST',
    USAER_DATA = 'USAER_DATA',
    PLAYER_READY = 'PLAYER_READY',
    START_ROUND = 'START_ROUND',
    STOP_COUNTING = 'STOP_COUNTING',
    COUNTING_STOPPED = 'COUNTING_STOPPED',
    HIT_POINT_CLICKED = 'HIT_POINT_CLICKED',
    ROUND_WON = 'ROUND_WON',
    ROUND_LOST = 'ROUND_LOST'
}
